import fs from 'node:fs/promises';
import path from 'node:path';
import {marked} from 'marked';
import QRCode from 'qrcode';
const site=JSON.parse(await fs.readFile('content/site.json','utf8'));
if(process.env.SITE_URL)site.url=process.env.SITE_URL;
const articles=JSON.parse(await fs.readFile('content/articles.json','utf8')).sort((a,b)=>b.date.localeCompare(a.date));
const base=new URL(site.url);if(!site.url.endsWith('/')||base.protocol!=='https:')throw Error('Site URL must be an HTTPS directory');
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const href=p=>new URL(p,base).href;
const url=p=>base.pathname+p;
const out='dist';await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});await fs.cp('assets',out+'/assets',{recursive:true});await fs.mkdir(out+'/articles',{recursive:true});
const person={'@type':'Person','@id':href('#person'),name:'易波',alternateName:'Yi Bo',url:site.url,image:href('assets/yi-bo.jpg'),description:site.description,jobTitle:['东南大学法学院副教授','硕士生导师','东南大学人权研究院副院长','江苏益友天元（南京）律师事务所管理合伙人'],worksFor:[{'@type':'CollegeOrUniversity',name:'东南大学'},{'@type':'Organization',name:'江苏益友天元（南京）律师事务所'}],alumniOf:{'@type':'CollegeOrUniversity',name:'苏州大学'},knowsAbout:['国际经济法','商事争议解决','工商业人权法'],sameAs:[site.profileSource],...(site.contact.email?{email:site.contact.email}:{})};
const nav=`<header class="header"><div class="wrap nav"><a class="brand" href="${url('')}" aria-label="易波，返回首页"><span class="brand-cn">易波</span><span class="brand-en">YI BO</span></a><button class="menu" aria-expanded="false" aria-controls="navigation">菜单 ☰</button><nav class="navlinks" id="navigation" aria-label="主导航"><a href="${url('#about')}">关于易波</a><a href="${url('#research')}">专业领域</a><a href="${url('articles/')}">文章与动态</a><a href="${url('#contact')}" class="nav-contact">联系交流 <span aria-hidden="true">↗</span></a></nav></div></header>`;
function footer(){return `<footer class="wrap footer"><span>© ${new Date(site.updated).getFullYear()} 易波 · YI BO &nbsp; 学术 · 实务 · 公共交流</span><div class="footer-links"><a href="${url('feed.xml')}">RSS 订阅</a><button data-share>分享此页 ↗</button><a href="${site.profileSource}" target="_blank" rel="noopener">东南大学主页 ↗</a></div></footer><div class="mobile-contact"><span>易波 · 学术与实务</span><a href="${url('#contact')}">联系交流 ↗</a></div><div class="toast" role="status" hidden></div>`}
function share(page,qr){return `<dialog id="share-dialog" aria-labelledby="share-heading"><div class="dialog-top"><h2 id="share-heading">让交流，从这里开始</h2><button class="close" aria-label="关闭分享弹窗">×</button></div><img class="share-qr" src="${url(qr)}" width="190" height="190" alt="扫码打开当前页面"><p class="dialog-desc">微信扫一扫，或保存二维码分享给朋友。<br>微信内可点击右上角「···」转发。</p><input class="share-url" aria-label="分享链接" value="${e(href(page))}" readonly><div class="dialog-buttons"><button data-copy="${e(href(page))}">复制链接</button><a href="${url(qr)}" download="易波-分享二维码.png">保存二维码</a><button data-native-share>分享</button></div></dialog>`}
function shell({author=site.name,published,modified,title=site.title,desc=site.description,page='',body,schema=[],type='website',qr='assets/site-qr.png'}){return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#f7f5f0"><title>${e(title)}</title><meta name="description" content="${e(desc)}"><meta name="author" content="${e(author)}"><meta name="robots" content="index,follow,max-image-preview:large">${published?`<meta property="article:published_time" content="${e(published)}">`:""}${modified?`<meta property="article:modified_time" content="${e(modified)}">`:""}<link rel="canonical" href="${href(page)}"><meta property="og:type" content="${type}"><meta property="og:locale" content="zh_CN"><meta property="og:site_name" content="易波 · 学术与实务"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(desc)}"><meta property="og:url" content="${href(page)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(desc)}"><link rel="icon" type="image/svg+xml" href="${url('assets/favicon.svg')}"><link rel="alternate" type="application/rss+xml" title="易波 · 文章与动态" href="${url('feed.xml')}"><link rel="stylesheet" href="${url('assets/site.css')}"><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':schema})}</script><script src="${url('assets/site.js')}" defer></script></head><body><a class="skip" href="#main">跳转至正文</a>${nav}${body}${footer()}${share(page,qr)}</body></html>`}
function rows(items){return items.map(a=>`<a class="article-row" data-category="${e(a.category)}" href="${url('articles/'+a.slug+'/')}"><div class="article-meta"><time datetime="${a.date}">${a.date.replaceAll('-','.')}</time><span>${e(a.kind)}</span></div><div><h3>${e(a.title)}</h3><p>${e(a.summary)}</p></div><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}
const contact=site.contact;let contactHTML='';
if(contact.email)contactHTML+=`<a class="contact-item" href="mailto:${e(contact.email)}"><small>电子邮箱</small><span>${e(contact.email)} ↗</span></a>`;
if(contact.phone)contactHTML+=`<a class="contact-item" href="tel:${e(contact.phone.replace(/\s/g,''))}"><small>联系电话</small><span>${e(contact.phone)} ↗</span></a>`;
if(contact.wechat)contactHTML+=`<div class="contact-item"><small>微信</small><button data-copy="${e(contact.wechat)}">${e(contact.wechat)} &nbsp; 复制</button></div>`;
if(contact.officialAccountUrl)contactHTML+=`<a class="contact-item" href="${e(contact.officialAccountUrl)}" target="_blank" rel="noopener"><small>微信公众号</small><span>关注专业文章 ↗</span></a>`;
if(!contactHTML)contactHTML=`<a class="contact-item" href="${site.profileSource}" target="_blank" rel="noopener"><small>学术主页</small><span>东南大学法学院 ↗</span></a><p class="contact-note">个人联系渠道将于确认后公开。您也可以保存此页，方便后续交流。</p>`;
contactHTML+=`<div class="contact-item"><small>个人名片</small><button data-share>分享主页与二维码 ↗</button></div>`;
const body=`<main id="main"><div class="wrap"><section class="hero" aria-label="易波个人介绍"><div class="hero-copy"><div class="eyebrow">Scholar · Practitioner · Global Perspective</div><h1>易波</h1><p class="degrees">应用经济学博士后 &nbsp; / &nbsp; 法学博士</p><div class="hero-rule"></div><h2 class="hero-statement">以学术洞察法律，<br>以实践回应时代。</h2><p class="hero-roles">东南大学法学院副教授 · 硕士生导师<br>东南大学人权研究院副院长<br>江苏益友天元（南京）律师事务所管理合伙人</p><div class="hero-actions"><a class="button" href="#about">了解易波 <span aria-hidden="true">↗</span></a><a class="text-link" href="${url('articles/')}">阅读文章与动态 <span aria-hidden="true">→</span></a></div></div><figure class="portrait"><img src="${url('assets/yi-bo.jpg')}" width="1200" height="1043" alt="易波，身着深蓝西装的个人肖像" fetchpriority="high"><figcaption><span>YI BO / 易波</span><span>NANJING, CHINA</span></figcaption></figure></section><div class="discipline-strip"><span>RESEARCH & PRACTICE</span><span>国际经济法</span><span>商事争议解决</span><span>工商业人权法</span></div>
<section class="section" id="about"><div class="section-heading"><div><div class="eyebrow">01 / About</div><h2>在学术与实践之间</h2></div><p class="section-sub">立足法学与经济学的交叉视野，<br>关注全球规则、商业秩序与人的权利。</p></div><div class="about-grid"><div class="prose"><p>易波，<strong>应用经济学博士后、法学博士</strong>。现任东南大学法学院副教授、硕士生导师，东南大学人权研究院副院长，江苏益友天元（南京）律师事务所管理合伙人。</p><p>曾赴美国康奈尔大学法学院、加州大学洛杉矶分校法学院、新加坡国立大学访学。主要研究领域为<strong>国际经济法、商事争议解决、工商业人权法</strong>。</p><p>在教学、研究与法律实务中，持续关注国际规则与中国实践之间的对话；通过学术交流和国际会议，参与全球人权治理与商业法律问题的讨论。</p><div class="sources-note">履历依据个人简介资料整理 · <a href="${site.profileSource}" target="_blank" rel="noopener">查看学校公开介绍 ↗</a></div></div><div class="credentials"><div class="credential"><small>ACADEMIC / 学术背景</small><p>应用经济学博士后 · 东南大学<br>法学博士 · 苏州大学</p></div><div class="credential"><small>VISITING / 国际访学</small><p>康奈尔大学法学院<br>加州大学洛杉矶分校法学院<br>新加坡国立大学</p></div><div class="credential"><small>RECOGNITION / 代表荣誉</small><p>“一带一路”争议解决类十佳法律服务案例<br>江苏省智库研究与决策咨询优秀成果二等奖</p></div></div></div></section>
<section class="section" id="research"><div class="section-heading"><div><div class="eyebrow">02 / Areas of Focus</div><h2>三个方向，一个长期关切</h2></div><p class="section-sub">理解规则，解决争议，守护权利。</p></div><div class="areas"><article class="area"><span class="area-num">01</span><h3>国际经济法</h3><div class="area-en">INTERNATIONAL ECONOMIC LAW</div><p>关注跨境经贸活动中的国际规则与法律秩序，理解全球经济联系中的制度问题。</p></article><article class="area"><span class="area-num">02</span><h3>商事争议解决</h3><div class="area-en">COMMERCIAL DISPUTE RESOLUTION</div><p>围绕商业活动中的复杂争议，连接法律研究与司法实践，关注跨境争议的解决机制。</p></article><article class="area"><span class="area-num">03</span><h3>工商业人权法</h3><div class="area-en">BUSINESS AND HUMAN RIGHTS</div><p>探讨企业经营与人权保障的关系，关注商业发展中的责任、治理与权利保护。</p></article></div></section></div>
<div class="international"><section class="wrap section" id="international"><div class="eyebrow">03 / A Global Conversation</div><h2>让专业研究，<br>参与更广阔的国际对话。</h2><p class="intro">曾作为具有联合国咨商地位的社会组织代表，出席联合国人权理事会第57、58、59、60、61、62届会议，并在大会现场发言。</p><div class="facts"><div class="fact"><div class="number">6<small>届</small></div><p>联合国人权理事会会议<br>第57—62届 · 现场交流与发言</p></div><div class="fact"><div class="number">12<small>项</small></div><p>主持研究课题<br>包括教育部人文社科项目</p></div><div class="fact"><div class="number">3<small>所</small></div><p>海外高校访学<br>康奈尔 · UCLA · 新加坡国立大学</p></div></div><a class="text-link" href="https://news.seu.edu.cn/2024/0919/c5541a503352/page.htm" target="_blank" rel="noopener">阅读第57届会议学校报道 <span aria-hidden="true">↗</span></a></section></div>
<div class="wrap"><section class="section" id="insights"><div class="section-heading"><div><div class="eyebrow">04 / Writing & Updates</div><h2>文章与动态</h2></div><a class="text-link" href="${url('articles/')}">查看全部 <span aria-hidden="true">↗</span></a></div>${rows(articles.slice(0,3))}<p class="sources-note">当前收录学术讲座与公开报道，均附原始出处。署名专业文章将持续更新。</p></section><section class="section contact" id="contact"><div><div class="eyebrow">05 / Get in Touch</div><h2>从一次交流开始</h2><p class="contact-copy">欢迎围绕学术研究、专业讲座与法律实务展开交流。联系时，可简要说明您的机构、关注议题及交流意向。</p></div><div><div class="contact-list">${contactHTML}</div><p class="contact-note">南京，中国 · 学术交流与专业合作</p></div></section></div></main>`;
await QRCode.toFile(out+'/assets/site-qr.png',site.url,{width:600,margin:3,color:{dark:'#182c38',light:'#ffffff'},errorCorrectionLevel:'M'});
await fs.writeFile(out+'/index.html',shell({body,schema:[person,{'@type':'ProfilePage','@id':site.url,url:site.url,name:site.title,dateModified:site.updated,mainEntity:{'@id':href('#person')}},{'@type':'WebSite',name:'易波 · 学术与实务',url:site.url,inLanguage:'zh-CN'}]}));
const categories=['全部',...new Set(articles.map(a=>a.category))];
await fs.writeFile(out+'/articles/index.html',shell({page:'articles/',title:'文章与动态｜易波',desc:'易波的专业文章、学术讲座、国际交流与研究动态。每篇公开报道均可追溯至原始来源。',body:`<main class="wrap" id="main"><section class="archive-intro"><div class="eyebrow">Writing & Updates</div><h1>文章与动态</h1><p class="section-sub">研究的积累，实践的记录，持续的对话。</p></section><label for="article-search" class="eyebrow">搜索文章</label><input class="search" id="article-search" type="search" placeholder="输入主题或关键词"><div class="filters" role="group" aria-label="按领域筛选">${categories.map(c=>`<button class="filter" data-filter="${e(c)}" aria-pressed="${c==='全部'}">${e(c)}</button>`).join('')}</div><p class="sources-note" id="result-status" role="status">共 ${articles.length} 篇内容</p><section aria-label="文章列表">${rows(articles)}</section><p class="empty" hidden>暂未找到相关内容，试试其他关键词。</p><p class="sources-note">公开报道为摘要整理，附原始出处；署名文章会明确标注作者。</p></main>`,schema:[{'@type':'CollectionPage',name:'文章与动态｜易波',url:href('articles/'),mainEntity:{'@type':'ItemList',itemListElement:articles.map((a,i)=>({'@type':'ListItem',position:i+1,url:href('articles/'+a.slug+'/'),name:a.title}))}}],qr:'assets/archive-qr.png'}));
await QRCode.toFile(out+'/assets/archive-qr.png',href('articles/'),{width:600,margin:3});
const seen=new Set();for(const a of articles){if(!/^[a-z0-9-]+$/.test(a.slug)||seen.has(a.slug))throw Error('Invalid/duplicate slug');seen.add(a.slug);if(!/^\d{4}-\d{2}-\d{2}$/.test(a.date))throw Error('Invalid date');if(a.source&&!/^https:\/\//.test(a.source))throw Error('Source must use https');if(path.basename(a.content)!==a.content)throw Error('Content must be filename');
const page='articles/'+a.slug+'/';await fs.mkdir(out+'/'+page,{recursive:true});const md=await fs.readFile('content/articles/'+a.content,'utf8');if(/<\/?[a-z]|\]\(\s*(javascript:|data:)/i.test(md))throw Error('Use safe Markdown, no raw HTML');const articleBody=marked.parse(md);const qr='assets/'+a.slug+'-qr.png';await QRCode.toFile(out+'/'+qr,href(page),{width:600,margin:3});
await fs.writeFile(out+'/'+page+'index.html',shell({page,author:a.author,published:a.date,modified:a.updated||a.date,title:a.title+'｜易波',desc:a.summary,type:'article',qr,body:`<main class="wrap" id="main"><article class="reading"><div class="breadcrumb"><a href="${url('')}">首页</a> / <a href="${url('articles/')}">文章与动态</a></div><div class="eyebrow">${e(a.kind)} / ${e(a.category)}</div><h1>${e(a.title)}</h1><div class="reading-meta"><time datetime="${a.date}">${a.date.replaceAll('-','.')}</time> &nbsp; · &nbsp; ${a.source?'来源':'作者'}：${e(a.sourceName||a.author)}${a.source?' · 公开报道摘要':''}</div><div class="reading-body">${articleBody}</div>${a.source?`<aside class="source-box">本文依据公开报道整理。<br><a href="${e(a.source)}" target="_blank" rel="noopener">阅读${e(a.sourceName)}原文 ↗</a></aside>`:''}<div class="reading-actions"><a class="text-link" href="${url('articles/')}">← 返回文章列表</a><button data-share>分享本文与二维码 ↗</button></div></article></main>`,schema:[{'@type':'Article',headline:a.title,description:a.summary,inLanguage:'zh-CN',datePublished:a.date,dateModified:a.updated||a.date,mainEntityOfPage:href(page),url:href(page),author:a.source?{'@type':'Organization',name:a.author,url:new URL(a.source).origin}:{'@id':href('#person')},about:{'@id':href('#person')},...(a.source?{citation:a.source}:{}),publisher:{'@id':href('#person')}},person,{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'首页',item:site.url},{'@type':'ListItem',position:2,name:'文章与动态',item:href('articles/')},{'@type':'ListItem',position:3,name:a.title,item:href(page)}]}]}));}
await fs.writeFile(out+'/404.html',shell({title:'页面未找到｜易波',page:'404.html',body:`<main class="wrap reading" id="main"><div class="eyebrow">404</div><h1>这一页暂时不在这里</h1><p>您可以返回首页，或查看最新文章。</p><a class="button" href="${url('')}">返回首页 →</a></main>`}).replace('index,follow,max-image-preview:large','noindex,follow'));
const xml=e;const routes=[['',site.updated],['articles/',site.updated],...articles.map(a=>['articles/'+a.slug+'/',a.updated||a.date])];
await fs.writeFile(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(([p,d])=>`<url><loc>${xml(href(p))}</loc><lastmod>${d}</lastmod></url>`).join('')}</urlset>`);
await fs.writeFile(out+'/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${href('sitemap.xml')}\n`);
await fs.writeFile(out+'/llms.txt',`# 易波 / Yi Bo\n\n> ${site.description}\n\n## 事实来源\n\n- [个人主页](${site.url})：当前个人简介，以个人简介资料为基础。\n- [东南大学法学院公开介绍](${site.profileSource})：学校公开资料，历史页面不一定包含最新任职。\n\n## 专业领域\n\n国际经济法；商事争议解决；工商业人权法。\n\n## 文章与动态\n\n${articles.map(a=>`- [${a.title}](${href('articles/'+a.slug+'/')})：${a.summary}`).join('\n')}\n\n## 引用说明\n\n本网站的报道摘要不是署名论文或发言全文。引用时请保留日期、作者及原始来源，不要将社会组织代表身份表述为联合国任职。\n`);
await fs.writeFile(out+'/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>易波 · 文章与动态</title><link>${xml(site.url)}</link><description>${xml(site.description)}</description><language>zh-CN</language>${articles.map(a=>`<item><title>${xml(a.title)}</title><link>${xml(href('articles/'+a.slug+'/'))}</link><guid>${xml(href('articles/'+a.slug+'/'))}</guid><pubDate>${new Date(a.date+'T00:00:00Z').toUTCString()}</pubDate><description>${xml(a.summary)}</description></item>`).join('')}</channel></rss>`);
await fs.writeFile(out+'/.nojekyll','');console.log(`Built homepage, archive, ${articles.length} article pages, sitemap, RSS and sharing QR codes.`);
